package smarthome

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// Device represents a smart home device known to the agent.
type Device struct {
	EntityID string `json:"entity_id"`
	Name     string `json:"name"`
	Room     string `json:"room"`
	Platform string `json:"platform"` // tuya, tmall, xiaomi
	Type     string `json:"type"`     // light, switch, sensor, climate, lock, curtain
}

// EntityState represents the current state of a Home Assistant entity.
type EntityState struct {
	EntityID    string                 `json:"entity_id"`
	State       string                 `json:"state"`
	Attributes  map[string]interface{} `json:"attributes"`
	LastChanged time.Time              `json:"last_changed"`
	LastUpdated time.Time              `json:"last_updated"`
}

// HistoryEntry is a single historical record for an entity.
type HistoryEntry struct {
	EntityID   string                 `json:"entity_id"`
	State      string                 `json:"state"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Timestamp  time.Time              `json:"last_changed"`
}

// AutomationConfig describes a Home Assistant automation rule.
type AutomationConfig struct {
	ID          string                `json:"id"`
	Alias       string                `json:"alias"`
	Description string                `json:"description,omitempty"`
	Trigger     []AutomationTrigger   `json:"trigger"`
	Condition   []AutomationCondition `json:"condition,omitempty"`
	Action      []AutomationAction    `json:"action"`
	Mode        string                `json:"mode,omitempty"`
}

// Unsupported HA fields must fail instead of weakening a condition during decoding.
func (a *AutomationConfig) UnmarshalJSON(data []byte) error {
	type plainAutomation AutomationConfig
	var decoded plainAutomation
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return fmt.Errorf("%w: %v", ErrUnsupportedRule, err)
	}
	*a = AutomationConfig(decoded)
	return nil
}

// These types describe the supported, explicit subset of HA automation syntax.
// Natural-language labels on RuleSuggestion are never interpreted as commands.
type AutomationTrigger struct {
	Platform string `json:"platform"`
	At       string `json:"at,omitempty"`
	EntityID string `json:"entity_id,omitempty"`
	From     string `json:"from,omitempty"`
	To       string `json:"to,omitempty"`
}

type AutomationCondition struct {
	Condition string `json:"condition"`
	EntityID  string `json:"entity_id"`
	State     string `json:"state"`
}

type AutomationTarget struct {
	EntityID string `json:"entity_id"`
}

type AutomationAction struct {
	Service string           `json:"service"`
	Target  AutomationTarget `json:"target"`
}

// HAEvent is a Home Assistant event received via WebSocket.
type HAEvent struct {
	ID      int          `json:"id"`
	Type    string       `json:"type"` // "event", "result"
	Event   *HAEventData `json:"event,omitempty"`
	Success *bool        `json:"success,omitempty"`
	Error   *HAError     `json:"error,omitempty"`
}

// HAEventData carries the event type and data payload.
type HAEventData struct {
	EventType string                 `json:"event_type"`
	Data      map[string]interface{} `json:"data"`
	TimeFired time.Time              `json:"time_fired"`
}

// HAError represents a Home Assistant API error.
type HAError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// EventHandler is called for each HA event received via WebSocket.
type EventHandler func(event HAEvent)

// RuleSuggestion is a proposed automation rule generated by the analysis engine.
type RuleSuggestion struct {
	ID             string            `json:"id"`
	Title          string            `json:"title"`
	Description    string            `json:"description"`
	Trigger        string            `json:"trigger"`
	Condition      string            `json:"condition"`
	Action         string            `json:"action"`
	Confidence     float64           `json:"confidence"`
	DataSource     string            `json:"data_source"` // e.g. "14-day history, 93% hit rate"
	CreatedAt      time.Time         `json:"created_at"`
	Status         string            `json:"status"` // pending, applying, confirmed, failed, ignored
	Automation     *AutomationConfig `json:"automation,omitempty"`
	HAAutomationID string            `json:"ha_automation_id,omitempty"`
	LastError      string            `json:"last_error,omitempty"`
}

// DeviceReport is a periodic analysis report for smart home data.
type DeviceReport struct {
	PeriodStart time.Time         `json:"period_start"`
	PeriodEnd   time.Time         `json:"period_end"`
	Devices     []DeviceSummary   `json:"devices"`
	Patterns    []DetectedPattern `json:"patterns"`
	Suggestions []RuleSuggestion  `json:"suggestions"`
}

// DeviceSummary aggregates data for a single device over a period.
type DeviceSummary struct {
	EntityID     string  `json:"entity_id"`
	Name         string  `json:"name"`
	Room         string  `json:"room"`
	Type         string  `json:"type"`
	OnCount      int     `json:"on_count"`
	OffCount     int     `json:"off_count"`
	AvgOnHour    float64 `json:"avg_on_hour"`
	TotalOnTime  float64 `json:"total_on_time_hours"`
	AnomalyCount int     `json:"anomaly_count"`
}

// DetectedPattern represents a usage pattern found by the analysis engine.
type DetectedPattern struct {
	Type        string  `json:"type"` // time, correlation, anomaly, energy
	EntityID    string  `json:"entity_id"`
	RelatedID   string  `json:"related_id,omitempty"`
	Description string  `json:"description"`
	Confidence  float64 `json:"confidence"`
	SampleSize  int     `json:"sample_size"`
	PeriodDays  int     `json:"period_days"`
	TimeOfDay   string  `json:"time_of_day,omitempty"`
}

// HAConfig holds the Home Assistant connection configuration.
type HAConfig struct {
	BaseURL string `mapstructure:"base_url"`
	Token   string `mapstructure:"token"`
	// PollInterval is how often to pull history data from HA.
	PollIntervalSec int `mapstructure:"poll_interval_sec"`
	// AnalysisHour is the hour (0-23) when daily analysis runs.
	AnalysisHour int `mapstructure:"analysis_hour"`
	// AgentVaultPath is where rule documents and reports are written.
	AgentVaultPath string `mapstructure:"agent_vault_path"`
}
